'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Espanol
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Datos.Espanol", GetType(Espanol).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actualizar.
        '''</summary>
        Friend Shared ReadOnly Property btnActualizar() As String
            Get
                Return ResourceManager.GetString("btnActualizar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administradores.
        '''</summary>
        Friend Shared ReadOnly Property btnAdministradores() As String
            Get
                Return ResourceManager.GetString("btnAdministradores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar.
        '''</summary>
        Friend Shared ReadOnly Property btnAgregar() As String
            Get
                Return ResourceManager.GetString("btnAgregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Asociar.
        '''</summary>
        Friend Shared ReadOnly Property btnAsociar() As String
            Get
                Return ResourceManager.GetString("btnAsociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desasociar.
        '''</summary>
        Friend Shared ReadOnly Property btnDesasociar() As String
            Get
                Return ResourceManager.GetString("btnDesasociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  Historial de diagnosticos.
        '''</summary>
        Friend Shared ReadOnly Property btnDiagnosticos() As String
            Get
                Return ResourceManager.GetString("btnDiagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminar.
        '''</summary>
        Friend Shared ReadOnly Property btnEliminar() As String
            Get
                Return ResourceManager.GetString("btnEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enviar.
        '''</summary>
        Friend Shared ReadOnly Property btnEnviar() As String
            Get
                Return ResourceManager.GetString("btnEnviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mi información.
        '''</summary>
        Friend Shared ReadOnly Property btnInfo() As String
            Get
                Return ResourceManager.GetString("btnInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Iniciar sesión.
        '''</summary>
        Friend Shared ReadOnly Property btnIniciar() As String
            Get
                Return ResourceManager.GetString("btnIniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Iniciar chat.
        '''</summary>
        Friend Shared ReadOnly Property btnIniciarChat() As String
            Get
                Return ResourceManager.GetString("btnIniciarChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médicos.
        '''</summary>
        Friend Shared ReadOnly Property btnMedicos() As String
            Get
                Return ResourceManager.GetString("btnMedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property btnModificar() As String
            Get
                Return ResourceManager.GetString("btnModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property btnPacientes() As String
            Get
                Return ResourceManager.GetString("btnPacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologías.
        '''</summary>
        Friend Shared ReadOnly Property btnPatologias() As String
            Get
                Return ResourceManager.GetString("btnPatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Realizar consulta.
        '''</summary>
        Friend Shared ReadOnly Property btnRC() As String
            Get
                Return ResourceManager.GetString("btnRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salir.
        '''</summary>
        Friend Shared ReadOnly Property btnSalir() As String
            Get
                Return ResourceManager.GetString("btnSalir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property btnSintomas() As String
            Get
                Return ResourceManager.GetString("btnSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solicitudes de chat.
        '''</summary>
        Friend Shared ReadOnly Property btnSolicitudes() As String
            Get
                Return ResourceManager.GetString("btnSolicitudes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Volver.
        '''</summary>
        Friend Shared ReadOnly Property btnVolver() As String
            Get
                Return ResourceManager.GetString("btnVolver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Asociar síntomas y patologías.
        '''</summary>
        Friend Shared ReadOnly Property lblAsociarSP() As String
            Get
                Return ResourceManager.GetString("lblAsociarSP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¡Bienvenido!.
        '''</summary>
        Friend Shared ReadOnly Property lblBienvenido() As String
            Get
                Return ResourceManager.GetString("lblBienvenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Que tenga buena jornada,.
        '''</summary>
        Friend Shared ReadOnly Property lblBuenaJornada() As String
            Get
                Return ResourceManager.GetString("lblBuenaJornada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calle:.
        '''</summary>
        Friend Shared ReadOnly Property lblCalle() As String
            Get
                Return ResourceManager.GetString("lblCalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CI:.
        '''</summary>
        Friend Shared ReadOnly Property lblCedula() As String
            Get
                Return ResourceManager.GetString("lblCedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Código:.
        '''</summary>
        Friend Shared ReadOnly Property lblCodigo() As String
            Get
                Return ResourceManager.GetString("lblCodigo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña:.
        '''</summary>
        Friend Shared ReadOnly Property lblContraseña() As String
            Get
                Return ResourceManager.GetString("lblContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnóstico primario.
        '''</summary>
        Friend Shared ReadOnly Property lblDiagnostico() As String
            Get
                Return ResourceManager.GetString("lblDiagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Debes hacer doble click para iniciar el chat).
        '''</summary>
        Friend Shared ReadOnly Property lblDobleClick() As String
            Get
                Return ResourceManager.GetString("lblDobleClick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especialidad:.
        '''</summary>
        Friend Shared ReadOnly Property lblEspecialidad() As String
            Get
                Return ResourceManager.GetString("lblEspecialidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especialista:.
        '''</summary>
        Friend Shared ReadOnly Property lblEspecialista() As String
            Get
                Return ResourceManager.GetString("lblEspecialista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esquina:.
        '''</summary>
        Friend Shared ReadOnly Property lblEsquina() As String
            Get
                Return ResourceManager.GetString("lblEsquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gestion de administradores.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionAdmins() As String
            Get
                Return ResourceManager.GetString("lblGestionAdmins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gestion de médicos.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionMedicos() As String
            Get
                Return ResourceManager.GetString("lblGestionMedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gestion de pacientes.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionPacientes() As String
            Get
                Return ResourceManager.GetString("lblGestionPacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gestión de patologías.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionPatologias() As String
            Get
                Return ResourceManager.GetString("lblGestionPatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gestion de síntomas.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionSintomas() As String
            Get
                Return ResourceManager.GetString("lblGestionSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gravedad:.
        '''</summary>
        Friend Shared ReadOnly Property lblGravedad() As String
            Get
                Return ResourceManager.GetString("lblGravedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medico:.
        '''</summary>
        Friend Shared ReadOnly Property lblMedico() As String
            Get
                Return ResourceManager.GetString("lblMedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nacimiento:.
        '''</summary>
        Friend Shared ReadOnly Property lblNacimiento() As String
            Get
                Return ResourceManager.GetString("lblNacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property lblNombre() As String
            Get
                Return ResourceManager.GetString("lblNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Número:.
        '''</summary>
        Friend Shared ReadOnly Property lblNum() As String
            Get
                Return ResourceManager.GetString("lblNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patología:.
        '''</summary>
        Friend Shared ReadOnly Property lblPatologia() As String
            Get
                Return ResourceManager.GetString("lblPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patología final:.
        '''</summary>
        Friend Shared ReadOnly Property lblPatologiaFinal() As String
            Get
                Return ResourceManager.GetString("lblPatologiaFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1er apellido:.
        '''</summary>
        Friend Shared ReadOnly Property lblPrimApe() As String
            Get
                Return ResourceManager.GetString("lblPrimApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 2do apellido:.
        '''</summary>
        Friend Shared ReadOnly Property lblSegApe() As String
            Get
                Return ResourceManager.GetString("lblSegApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sexo:.
        '''</summary>
        Friend Shared ReadOnly Property lblSexo() As String
            Get
                Return ResourceManager.GetString("lblSexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property lblSintoma() As String
            Get
                Return ResourceManager.GetString("lblSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solicitudes de chat.
        '''</summary>
        Friend Shared ReadOnly Property lblSolicitudes() As String
            Get
                Return ResourceManager.GetString("lblSolicitudes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Teléfono:.
        '''</summary>
        Friend Shared ReadOnly Property lblTel() As String
            Get
                Return ResourceManager.GetString("lblTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario:.
        '''</summary>
        Friend Shared ReadOnly Property lblUsuario() As String
            Get
                Return ResourceManager.GetString("lblUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Solo puedes realizar un máximo de 4 consultas por día..
        '''</summary>
        Friend Shared ReadOnly Property msg4Consultas() As String
            Get
                Return ResourceManager.GetString("msg4Consultas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El apellido no puede contener números..
        '''</summary>
        Friend Shared ReadOnly Property msgApellidoNumeros() As String
            Get
                Return ResourceManager.GetString("msgApellidoNumeros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha asociado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgAsociadoExito() As String
            Get
                Return ResourceManager.GetString("msgAsociadoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Atención.
        '''</summary>
        Friend Shared ReadOnly Property msgAtencion() As String
            Get
                Return ResourceManager.GetString("msgAtencion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La cédula ingresada es incorrecta..
        '''</summary>
        Friend Shared ReadOnly Property msgCedulaIncorrecta() As String
            Get
                Return ResourceManager.GetString("msgCedulaIncorrecta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La cédula no coincide con la de un usuario ingresado..
        '''</summary>
        Friend Shared ReadOnly Property msgCedulaNoCoincide() As String
            Get
                Return ResourceManager.GetString("msgCedulaNoCoincide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La contraseña debe tener un mínimo de 8 caracteres..
        '''</summary>
        Friend Shared ReadOnly Property msgContraseñaCaracteres() As String
            Get
                Return ResourceManager.GetString("msgContraseñaCaracteres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos modificados correctamente!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatosActualizados() As String
            Get
                Return ResourceManager.GetString("msgDatosActualizados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha desasociado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgDesasociadoExito() As String
            Get
                Return ResourceManager.GetString("msgDesasociadoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debes seleccionar un mínimo de 2 síntomas..
        '''</summary>
        Friend Shared ReadOnly Property msgDosSintomas() As String
            Get
                Return ResourceManager.GetString("msgDosSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al intentar asociar..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorAsociar() As String
            Get
                Return ResourceManager.GetString("msgErrorAsociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al intentar desasociar..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorDesasociar() As String
            Get
                Return ResourceManager.GetString("msgErrorDesasociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Se produjo un problema al intenar obtener el diagnóstico..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorDiagnostico() As String
            Get
                Return ResourceManager.GetString("msgErrorDiagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al eliminar..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminar() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al eliminar la patología..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminarPatologia() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al eliminar el síntoma.
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminarSintoma() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al eliminar el usuario..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminarUsuario() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al enviar el mensaje..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEnviarMensaje() As String
            Get
                Return ResourceManager.GetString("msgErrorEnviarMensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al ingresar la patología..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIngresarPatologia() As String
            Get
                Return ResourceManager.GetString("msgErrorIngresarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al ingresar el síntoma..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIngresarSintoma() As String
            Get
                Return ResourceManager.GetString("msgErrorIngresarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al ingresar el usuario..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIngresarUsuario() As String
            Get
                Return ResourceManager.GetString("msgErrorIngresarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La cédula y la contraseña no coinciden con ningún usuario..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIniciar() As String
            Get
                Return ResourceManager.GetString("msgErrorIniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al insertar..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorInsertar() As String
            Get
                Return ResourceManager.GetString("msgErrorInsertar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al modificar..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificar() As String
            Get
                Return ResourceManager.GetString("msgErrorModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al modificar la patología..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificarPatologia() As String
            Get
                Return ResourceManager.GetString("msgErrorModificarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al modificar el síntoma..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificarSintoma() As String
            Get
                Return ResourceManager.GetString("msgErrorModificarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al modificar el usuario..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificarUsuario() As String
            Get
                Return ResourceManager.GetString("msgErrorModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al intentar realizar la consulta..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorRealizarConsulta() As String
            Get
                Return ResourceManager.GetString("msgErrorRealizarConsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ocurrió un problema al obtener la información de la tabla..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorTabla() As String
            Get
                Return ResourceManager.GetString("msgErrorTabla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debes seleccionar los valores..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorValores() As String
            Get
                Return ResourceManager.GetString("msgErrorValores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La gravedad debe ser un número entre el 1 y el 5..
        '''</summary>
        Friend Shared ReadOnly Property msgGravedadMenor5() As String
            Get
                Return ResourceManager.GetString("msgGravedadMenor5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debes ingresar la CI..
        '''</summary>
        Friend Shared ReadOnly Property msgIngresarCedula() As String
            Get
                Return ResourceManager.GetString("msgIngresarCedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debe ingresar una contraseña..
        '''</summary>
        Friend Shared ReadOnly Property msgIngresarContraseña() As String
            Get
                Return ResourceManager.GetString("msgIngresarContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese una patología.
        '''</summary>
        Friend Shared ReadOnly Property msgIngresePatologia() As String
            Get
                Return ResourceManager.GetString("msgIngresePatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese un síntoma.
        '''</summary>
        Friend Shared ReadOnly Property msgIngreseSintoma() As String
            Get
                Return ResourceManager.GetString("msgIngreseSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Puedes seleccionar un máximo de 8 síntomas..
        '''</summary>
        Friend Shared ReadOnly Property msgMaximo8Sintomas() As String
            Get
                Return ResourceManager.GetString("msgMaximo8Sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El síntoma no esá asociado..
        '''</summary>
        Friend Shared ReadOnly Property msgNoAsociado() As String
            Get
                Return ResourceManager.GetString("msgNoAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El nombre no puede contener números..
        '''</summary>
        Friend Shared ReadOnly Property msgNombreNumeros() As String
            Get
                Return ResourceManager.GetString("msgNombreNumeros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debes ingresar el nombre del síntoma..
        '''</summary>
        Friend Shared ReadOnly Property msgNombreSintoma() As String
            Get
                Return ResourceManager.GetString("msgNombreSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La cédula no se puede repetir con la de otro usuario..
        '''</summary>
        Friend Shared ReadOnly Property msgNoRepetirCedula() As String
            Get
                Return ResourceManager.GetString("msgNoRepetirCedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El mail no se puede repetir con el de otro usuario..
        '''</summary>
        Friend Shared ReadOnly Property msgNoRepetirMail() As String
            Get
                Return ResourceManager.GetString("msgNoRepetirMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patología eliminada con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaEliminada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaEliminada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patología ingresada con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaIngresada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaIngresada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patología modificada con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaModificada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaModificada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: La patología que intentas modificar no está ingresada..
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaNoIngresada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaNoIngresada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Ya existe una patología con ese nombre..
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaYaIngresada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaYaIngresada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debes rellenar todos los campos..
        '''</summary>
        Friend Shared ReadOnly Property msgRellenarCampos() As String
            Get
                Return ResourceManager.GetString("msgRellenarCampos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Debes ingresar el código..
        '''</summary>
        Friend Shared ReadOnly Property msgRellenarCodigo() As String
            Get
                Return ResourceManager.GetString("msgRellenarCodigo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Estás seguro de que quieres salir de la alpicación?.
        '''</summary>
        Friend Shared ReadOnly Property msgSalirApp() As String
            Get
                Return ResourceManager.GetString("msgSalirApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Estás seguro de que quieres salir de la aplicación? Si lo haces, no podrás volver a entrar al chat..
        '''</summary>
        Friend Shared ReadOnly Property msgSalirChat() As String
            Get
                Return ResourceManager.GetString("msgSalirChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea agregar la patología?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAgregarPatologia() As String
            Get
                Return ResourceManager.GetString("msgSeguroAgregarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea agregar el síntoma?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAgregarSintoma() As String
            Get
                Return ResourceManager.GetString("msgSeguroAgregarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea agregar al usuario?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAgregarUsuario() As String
            Get
                Return ResourceManager.GetString("msgSeguroAgregarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea asociar?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAsociar() As String
            Get
                Return ResourceManager.GetString("msgSeguroAsociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea desasociar?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroDesasociar() As String
            Get
                Return ResourceManager.GetString("msgSeguroDesasociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea eliminar la patología?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroEliminarPatologia() As String
            Get
                Return ResourceManager.GetString("msgSeguroEliminarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea eliminar el síntoma?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroEliminarSintoma() As String
            Get
                Return ResourceManager.GetString("msgSeguroEliminarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea eliminar al usuario?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroEliminarUsuario() As String
            Get
                Return ResourceManager.GetString("msgSeguroEliminarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea modificar su información?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarInfo() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea modificar la patología?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarPatologia() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea modificar el síntoma?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarSintoma() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Seguro que desea modificar al usuario?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarUsuario() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El sexo ingresado es incorrecto..
        '''</summary>
        Friend Shared ReadOnly Property msgSexo() As String
            Get
                Return ResourceManager.GetString("msgSexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntoma eliminado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaEliminado() As String
            Get
                Return ResourceManager.GetString("msgSintomaEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntoma ingresado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaIngresado() As String
            Get
                Return ResourceManager.GetString("msgSintomaIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntoma modificado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaModificado() As String
            Get
                Return ResourceManager.GetString("msgSintomaModificado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El síntoma que intentas modificar no está ingresado..
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaNoIngresado() As String
            Get
                Return ResourceManager.GetString("msgSintomaNoIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El síntoma ya está ingresado..
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaYaIngresado() As String
            Get
                Return ResourceManager.GetString("msgSintomaYaIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario eliminado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgUsuarioEliminadoExito() As String
            Get
                Return ResourceManager.GetString("msgUsuarioEliminadoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario ingresado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgUsuarioIngresado() As String
            Get
                Return ResourceManager.GetString("msgUsuarioIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario modificado con éxito!.
        '''</summary>
        Friend Shared ReadOnly Property msgUsuarioModificado() As String
            Get
                Return ResourceManager.GetString("msgUsuarioModificado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: El síntoma ya se encuentra asociado a la patología ingresada..
        '''</summary>
        Friend Shared ReadOnly Property msgYaAsociado() As String
            Get
                Return ResourceManager.GetString("msgYaAsociado", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
