'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Ingles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Datos.Ingles", GetType(Ingles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update.
        '''</summary>
        Friend Shared ReadOnly Property btnActualizar() As String
            Get
                Return ResourceManager.GetString("btnActualizar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aministrators.
        '''</summary>
        Friend Shared ReadOnly Property btnAdministradores() As String
            Get
                Return ResourceManager.GetString("btnAdministradores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add.
        '''</summary>
        Friend Shared ReadOnly Property btnAgregar() As String
            Get
                Return ResourceManager.GetString("btnAgregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Associate.
        '''</summary>
        Friend Shared ReadOnly Property btnAsociar() As String
            Get
                Return ResourceManager.GetString("btnAsociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desassociate.
        '''</summary>
        Friend Shared ReadOnly Property btnDesasociar() As String
            Get
                Return ResourceManager.GetString("btnDesasociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnostic history.
        '''</summary>
        Friend Shared ReadOnly Property btnDiagnosticos() As String
            Get
                Return ResourceManager.GetString("btnDiagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property btnEliminar() As String
            Get
                Return ResourceManager.GetString("btnEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Send.
        '''</summary>
        Friend Shared ReadOnly Property btnEnviar() As String
            Get
                Return ResourceManager.GetString("btnEnviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a My information.
        '''</summary>
        Friend Shared ReadOnly Property btnInfo() As String
            Get
                Return ResourceManager.GetString("btnInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property btnIniciar() As String
            Get
                Return ResourceManager.GetString("btnIniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start chat.
        '''</summary>
        Friend Shared ReadOnly Property btnIniciarChat() As String
            Get
                Return ResourceManager.GetString("btnIniciarChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctors.
        '''</summary>
        Friend Shared ReadOnly Property btnMedicos() As String
            Get
                Return ResourceManager.GetString("btnMedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify.
        '''</summary>
        Friend Shared ReadOnly Property btnModificar() As String
            Get
                Return ResourceManager.GetString("btnModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients.
        '''</summary>
        Friend Shared ReadOnly Property btnPacientes() As String
            Get
                Return ResourceManager.GetString("btnPacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property btnPatologias() As String
            Get
                Return ResourceManager.GetString("btnPatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Make a consultation.
        '''</summary>
        Friend Shared ReadOnly Property btnRC() As String
            Get
                Return ResourceManager.GetString("btnRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exit.
        '''</summary>
        Friend Shared ReadOnly Property btnSalir() As String
            Get
                Return ResourceManager.GetString("btnSalir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property btnSintomas() As String
            Get
                Return ResourceManager.GetString("btnSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat requests.
        '''</summary>
        Friend Shared ReadOnly Property btnSolicitudes() As String
            Get
                Return ResourceManager.GetString("btnSolicitudes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Return.
        '''</summary>
        Friend Shared ReadOnly Property btnVolver() As String
            Get
                Return ResourceManager.GetString("btnVolver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Associate symptoms and pathologies.
        '''</summary>
        Friend Shared ReadOnly Property lblAsociarSP() As String
            Get
                Return ResourceManager.GetString("lblAsociarSP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Welcome!.
        '''</summary>
        Friend Shared ReadOnly Property lblBienvenido() As String
            Get
                Return ResourceManager.GetString("lblBienvenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Have a nice day..
        '''</summary>
        Friend Shared ReadOnly Property lblBuenaJornada() As String
            Get
                Return ResourceManager.GetString("lblBuenaJornada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Street:.
        '''</summary>
        Friend Shared ReadOnly Property lblCalle() As String
            Get
                Return ResourceManager.GetString("lblCalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ID Nº:.
        '''</summary>
        Friend Shared ReadOnly Property lblCedula() As String
            Get
                Return ResourceManager.GetString("lblCedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Code:.
        '''</summary>
        Friend Shared ReadOnly Property lblCodigo() As String
            Get
                Return ResourceManager.GetString("lblCodigo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password:.
        '''</summary>
        Friend Shared ReadOnly Property lblContraseña() As String
            Get
                Return ResourceManager.GetString("lblContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primary diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property lblDiagnostico() As String
            Get
                Return ResourceManager.GetString("lblDiagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (You must double click to enter the chat).
        '''</summary>
        Friend Shared ReadOnly Property lblDobleClick() As String
            Get
                Return ResourceManager.GetString("lblDobleClick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Specialty:.
        '''</summary>
        Friend Shared ReadOnly Property lblEspecialidad() As String
            Get
                Return ResourceManager.GetString("lblEspecialidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Specialist:.
        '''</summary>
        Friend Shared ReadOnly Property lblEspecialista() As String
            Get
                Return ResourceManager.GetString("lblEspecialista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Corner:.
        '''</summary>
        Friend Shared ReadOnly Property lblEsquina() As String
            Get
                Return ResourceManager.GetString("lblEsquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrators management.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionAdmins() As String
            Get
                Return ResourceManager.GetString("lblGestionAdmins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctors management.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionMedicos() As String
            Get
                Return ResourceManager.GetString("lblGestionMedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients management.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionPacientes() As String
            Get
                Return ResourceManager.GetString("lblGestionPacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies management.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionPatologias() As String
            Get
                Return ResourceManager.GetString("lblGestionPatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms management.
        '''</summary>
        Friend Shared ReadOnly Property lblGestionSintomas() As String
            Get
                Return ResourceManager.GetString("lblGestionSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Severity:.
        '''</summary>
        Friend Shared ReadOnly Property lblGravedad() As String
            Get
                Return ResourceManager.GetString("lblGravedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor:.
        '''</summary>
        Friend Shared ReadOnly Property lblMedico() As String
            Get
                Return ResourceManager.GetString("lblMedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Birthdate:.
        '''</summary>
        Friend Shared ReadOnly Property lblNacimiento() As String
            Get
                Return ResourceManager.GetString("lblNacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name:.
        '''</summary>
        Friend Shared ReadOnly Property lblNombre() As String
            Get
                Return ResourceManager.GetString("lblNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number:.
        '''</summary>
        Friend Shared ReadOnly Property lblNum() As String
            Get
                Return ResourceManager.GetString("lblNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies:.
        '''</summary>
        Friend Shared ReadOnly Property lblPatologia() As String
            Get
                Return ResourceManager.GetString("lblPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Final pathology:.
        '''</summary>
        Friend Shared ReadOnly Property lblPatologiaFinal() As String
            Get
                Return ResourceManager.GetString("lblPatologiaFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Surname:.
        '''</summary>
        Friend Shared ReadOnly Property lblPrimApe() As String
            Get
                Return ResourceManager.GetString("lblPrimApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 2nd surname:.
        '''</summary>
        Friend Shared ReadOnly Property lblSegApe() As String
            Get
                Return ResourceManager.GetString("lblSegApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sex:.
        '''</summary>
        Friend Shared ReadOnly Property lblSexo() As String
            Get
                Return ResourceManager.GetString("lblSexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms:.
        '''</summary>
        Friend Shared ReadOnly Property lblSintoma() As String
            Get
                Return ResourceManager.GetString("lblSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat requests.
        '''</summary>
        Friend Shared ReadOnly Property lblSolicitudes() As String
            Get
                Return ResourceManager.GetString("lblSolicitudes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone Nº:.
        '''</summary>
        Friend Shared ReadOnly Property lblTel() As String
            Get
                Return ResourceManager.GetString("lblTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User:.
        '''</summary>
        Friend Shared ReadOnly Property lblUsuario() As String
            Get
                Return ResourceManager.GetString("lblUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You can only make a maximum of 4 queries per day..
        '''</summary>
        Friend Shared ReadOnly Property msg4Consultas() As String
            Get
                Return ResourceManager.GetString("msg4Consultas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Last name cannot contain numbers..
        '''</summary>
        Friend Shared ReadOnly Property msgApellidoNumeros() As String
            Get
                Return ResourceManager.GetString("msgApellidoNumeros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a It has been successfully associated!.
        '''</summary>
        Friend Shared ReadOnly Property msgAsociadoExito() As String
            Get
                Return ResourceManager.GetString("msgAsociadoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Atention.
        '''</summary>
        Friend Shared ReadOnly Property msgAtencion() As String
            Get
                Return ResourceManager.GetString("msgAtencion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The ID entered is incorrect..
        '''</summary>
        Friend Shared ReadOnly Property msgCedulaIncorrecta() As String
            Get
                Return ResourceManager.GetString("msgCedulaIncorrecta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The ID does not match that of a user entered..
        '''</summary>
        Friend Shared ReadOnly Property msgCedulaNoCoincide() As String
            Get
                Return ResourceManager.GetString("msgCedulaNoCoincide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The password must be at least 8 characters..
        '''</summary>
        Friend Shared ReadOnly Property msgContraseñaCaracteres() As String
            Get
                Return ResourceManager.GetString("msgContraseñaCaracteres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Data modified successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatosActualizados() As String
            Get
                Return ResourceManager.GetString("msgDatosActualizados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The symptom has been disassociated successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgDesasociadoExito() As String
            Get
                Return ResourceManager.GetString("msgDesasociadoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must select a minimum of 2 symptoms..
        '''</summary>
        Friend Shared ReadOnly Property msgDosSintomas() As String
            Get
                Return ResourceManager.GetString("msgDosSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: A problem occurred trying to associate..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorAsociar() As String
            Get
                Return ResourceManager.GetString("msgErrorAsociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: A problem occurred trying to detach..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorDesasociar() As String
            Get
                Return ResourceManager.GetString("msgErrorDesasociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: An error occurred while trying to get the diagnosis..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorDiagnostico() As String
            Get
                Return ResourceManager.GetString("msgErrorDiagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: A problem occurred while deleting..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminar() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The pathology could not be removed..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminarPatologia() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not delete..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminarSintoma() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not delete user..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEliminarUsuario() As String
            Get
                Return ResourceManager.GetString("msgErrorEliminarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: There was a problem sending the message..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorEnviarMensaje() As String
            Get
                Return ResourceManager.GetString("msgErrorEnviarMensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not enter pathology..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIngresarPatologia() As String
            Get
                Return ResourceManager.GetString("msgErrorIngresarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not enter symptom..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIngresarSintoma() As String
            Get
                Return ResourceManager.GetString("msgErrorIngresarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: User could not be registered..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIngresarUsuario() As String
            Get
                Return ResourceManager.GetString("msgErrorIngresarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The ID and password do not match any user..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorIniciar() As String
            Get
                Return ResourceManager.GetString("msgErrorIniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: There was a problem inserting..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorInsertar() As String
            Get
                Return ResourceManager.GetString("msgErrorInsertar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not modify..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificar() As String
            Get
                Return ResourceManager.GetString("msgErrorModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The pathology could not be modified..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificarPatologia() As String
            Get
                Return ResourceManager.GetString("msgErrorModificarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The symptom could not be modified..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificarSintoma() As String
            Get
                Return ResourceManager.GetString("msgErrorModificarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not modify..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorModificarUsuario() As String
            Get
                Return ResourceManager.GetString("msgErrorModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: A problem occurred while trying to query..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorRealizarConsulta() As String
            Get
                Return ResourceManager.GetString("msgErrorRealizarConsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Could not get table information..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorTabla() As String
            Get
                Return ResourceManager.GetString("msgErrorTabla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must select the values..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorValores() As String
            Get
                Return ResourceManager.GetString("msgErrorValores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: Severity must be a number between 1 and 5..
        '''</summary>
        Friend Shared ReadOnly Property msgGravedadMenor5() As String
            Get
                Return ResourceManager.GetString("msgGravedadMenor5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must enter an identity card..
        '''</summary>
        Friend Shared ReadOnly Property msgIngresarCedula() As String
            Get
                Return ResourceManager.GetString("msgIngresarCedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must enter a password..
        '''</summary>
        Friend Shared ReadOnly Property msgIngresarContraseña() As String
            Get
                Return ResourceManager.GetString("msgIngresarContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter a pathology.
        '''</summary>
        Friend Shared ReadOnly Property msgIngresePatologia() As String
            Get
                Return ResourceManager.GetString("msgIngresePatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter a symptom.
        '''</summary>
        Friend Shared ReadOnly Property msgIngreseSintoma() As String
            Get
                Return ResourceManager.GetString("msgIngreseSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You can select a maximum of 8 symptoms..
        '''</summary>
        Friend Shared ReadOnly Property msgMaximo8Sintomas() As String
            Get
                Return ResourceManager.GetString("msgMaximo8Sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The symptom is not associated..
        '''</summary>
        Friend Shared ReadOnly Property msgNoAsociado() As String
            Get
                Return ResourceManager.GetString("msgNoAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The name cannot contain numbers..
        '''</summary>
        Friend Shared ReadOnly Property msgNombreNumeros() As String
            Get
                Return ResourceManager.GetString("msgNombreNumeros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must fill in the name of the symptom..
        '''</summary>
        Friend Shared ReadOnly Property msgNombreSintoma() As String
            Get
                Return ResourceManager.GetString("msgNombreSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The ID cannot be repeated with the ID of another user..
        '''</summary>
        Friend Shared ReadOnly Property msgNoRepetirCedula() As String
            Get
                Return ResourceManager.GetString("msgNoRepetirCedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The email cannot be repeated with that of another user..
        '''</summary>
        Friend Shared ReadOnly Property msgNoRepetirMail() As String
            Get
                Return ResourceManager.GetString("msgNoRepetirMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology successfully removed!.
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaEliminada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaEliminada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology entered successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaIngresada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaIngresada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology updated successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaModificada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaModificada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The pathology you are trying to modify is not entered..
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaNoIngresada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaNoIngresada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: There is already a pathology with that name..
        '''</summary>
        Friend Shared ReadOnly Property msgPatologiaYaIngresada() As String
            Get
                Return ResourceManager.GetString("msgPatologiaYaIngresada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must fill in all the fields..
        '''</summary>
        Friend Shared ReadOnly Property msgRellenarCampos() As String
            Get
                Return ResourceManager.GetString("msgRellenarCampos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: You must fill in the code..
        '''</summary>
        Friend Shared ReadOnly Property msgRellenarCodigo() As String
            Get
                Return ResourceManager.GetString("msgRellenarCodigo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to exit the application?.
        '''</summary>
        Friend Shared ReadOnly Property msgSalirApp() As String
            Get
                Return ResourceManager.GetString("msgSalirApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to exit the chat? If you do, you will not be able to resume the chat..
        '''</summary>
        Friend Shared ReadOnly Property msgSalirChat() As String
            Get
                Return ResourceManager.GetString("msgSalirChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to add the pathology?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAgregarPatologia() As String
            Get
                Return ResourceManager.GetString("msgSeguroAgregarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to add the symptom?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAgregarSintoma() As String
            Get
                Return ResourceManager.GetString("msgSeguroAgregarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to add the user?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAgregarUsuario() As String
            Get
                Return ResourceManager.GetString("msgSeguroAgregarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to associate?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroAsociar() As String
            Get
                Return ResourceManager.GetString("msgSeguroAsociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to disassociate?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroDesasociar() As String
            Get
                Return ResourceManager.GetString("msgSeguroDesasociar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to eliminate the pathology?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroEliminarPatologia() As String
            Get
                Return ResourceManager.GetString("msgSeguroEliminarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to eliminate the symptom?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroEliminarSintoma() As String
            Get
                Return ResourceManager.GetString("msgSeguroEliminarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to delete the user?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroEliminarUsuario() As String
            Get
                Return ResourceManager.GetString("msgSeguroEliminarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to change your information?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarInfo() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to modify the pathology?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarPatologia() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarPatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to modify the symptom?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarSintoma() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarSintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to modify the user?.
        '''</summary>
        Friend Shared ReadOnly Property msgSeguroModificarUsuario() As String
            Get
                Return ResourceManager.GetString("msgSeguroModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The gender entered is incorrect..
        '''</summary>
        Friend Shared ReadOnly Property msgSexo() As String
            Get
                Return ResourceManager.GetString("msgSexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom removed successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaEliminado() As String
            Get
                Return ResourceManager.GetString("msgSintomaEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom entered successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaIngresado() As String
            Get
                Return ResourceManager.GetString("msgSintomaIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom updated successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaModificado() As String
            Get
                Return ResourceManager.GetString("msgSintomaModificado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The symptom you are trying to modify is not entered..
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaNoIngresado() As String
            Get
                Return ResourceManager.GetString("msgSintomaNoIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The symptom is already entered..
        '''</summary>
        Friend Shared ReadOnly Property msgSintomaYaIngresado() As String
            Get
                Return ResourceManager.GetString("msgSintomaYaIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User deleted successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgUsuarioEliminadoExito() As String
            Get
                Return ResourceManager.GetString("msgUsuarioEliminadoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User registered successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgUsuarioIngresado() As String
            Get
                Return ResourceManager.GetString("msgUsuarioIngresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Data modified successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgUsuarioModificado() As String
            Get
                Return ResourceManager.GetString("msgUsuarioModificado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: The symptom is already associated with the selected pathology..
        '''</summary>
        Friend Shared ReadOnly Property msgYaAsociado() As String
            Get
                Return ResourceManager.GetString("msgYaAsociado", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
